//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingApp
{
    using System;
    using System.ComponentModel;

    public partial class FabricStock
    {
        [DisplayName("Номер")]
        public int Id { get; set; }
        [DisplayName("Артикул")]
        public string IdFabric { get; set; }
        [DisplayName("Ширина")]
        public Nullable<double> Width { get; set; }
        [DisplayName("Единицы")]
        public Nullable<int> IdUnitWidth { get; set; }
        [DisplayName("Высота")]
        public Nullable<double> Height { get; set; }
        [DisplayName("Единицы")]
        public Nullable<int> IdUnitHeight { get; set; }
        [DisplayName("Закупочная цена")]
        public Nullable<double> PurchasePrice { get; set; }

        [Browsable(false)]
        public virtual Fabric Fabric { get; set; }
        [Browsable(false)]
        public virtual Unit Unit { get; set; }
        [Browsable(false)]
        public virtual Unit Unit1 { get; set; }
    }
}
