//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Fabric
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fabric()
        {
            this.OrderItem = new HashSet<OrderItem>();
            this.ScrapRule = new HashSet<ScrapRule>();
            this.FabricStock = new HashSet<FabricStock>();
        }

        [DisplayName("Номер")]
        public string Id { get; set; }
        [DisplayName("Название")]
        public string Name { get; set; }
        [DisplayName("Цвет")]
        public string Color { get; set; }
        [DisplayName("Рисунок")]
        public string Pattern { get; set; }
        [DisplayName("Состав")]
        public string Composition { get; set; }
        public override string ToString() => Name;

        [Browsable(false)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        [Browsable(false)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScrapRule> ScrapRule { get; set; }
        [Browsable(false)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FabricStock> FabricStock { get; set; }
    }
}
