//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingApp
{
    using System.ComponentModel;

    public partial class OrderItem
    {
        [DisplayName("Номер")]
        public int Id { get; set; }
        [DisplayName("Заказ")]
        public int IdOrder { get; set; }
        [DisplayName("Изделие")]
        public string IdProduct { get; set; }
        [DisplayName("Ткань")]
        public string IdFabric { get; set; }
        [DisplayName("Фурнитура")]
        public string IdFurniture { get; set; }
        [DisplayName("Граница")]
        public string IdBorder { get; set; }
        [DisplayName("Ширина")]
        public double Width { get; set; }
        [DisplayName("Единицы")]
        public int IdUnitWidth { get; set; }
        [DisplayName("Высота")]
        public double Height { get; set; }
        [DisplayName("Единицы")]
        public int IdUnitHeight { get; set; }
        [DisplayName("Цена")]
        public double Price { get; set; }
        [DisplayName("Угол поворота")]
        public int RotationAngle { get; set; }
        [DisplayName("Кол-во")]
        public int Amount { get; set; }
    

        [Browsable(false)] public virtual Fabric Fabric { get; set; }
        [Browsable(false)] public virtual Furniture Furniture { get; set; }
        [Browsable(false)] public virtual Order Order { get; set; }
        [Browsable(false)] public virtual Unit Unit { get; set; }
        [Browsable(false)] public virtual Unit Unit1 { get; set; }
        [Browsable(false)] public virtual Product Product { get; set; }
    }
}
