//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    [DefaultProperty("Id")]
    [DefaultBindingProperty("Name")]
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        [DisplayName("Номер")]
        public string Id { get; set; }
        [DisplayName("Название")]
        public string Name { get; set; }
        [DisplayName("Описание")]
        public string Description { get; set; }
        [DisplayName("Ширина")]
        public Nullable<double> Width { get; set; }
        [DisplayName("Единицы")]
        public Nullable<int> IdUnitWidth { get; set; }
        [DisplayName("Высота")]
        public Nullable<double> Height { get; set; }
        [DisplayName("Единицы")]
        public Nullable<int> IdUnitHeight { get; set; }

        [Browsable(false)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        [Browsable(false)] public virtual Unit Unit { get; set; }
        [Browsable(false)] public virtual Unit Unit1 { get; set; }
    }
}
