//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingApp
{
    using System.ComponentModel;

    public partial class UnitConvert
    {
        [DisplayName("Номер")]
        public int Id { get; set; }
        [DisplayName("Из")]
        public int IdUnit1 { get; set; }
        [DisplayName("В")]
        public int IdUnit2 { get; set; }
        [DisplayName("Разница")]
        public double Ratio { get; set; }
    
        [Browsable(false)] public virtual Unit Unit { get; set; }
        [Browsable(false)] public virtual Unit Unit1 { get; set; }
    }
}
